fix: terraform-ec2-ssm type errors and minimum disk size
FIXES:
- Convert number/boolean to string for terraform:apply action
  - root_volume_size: quoted as string
  - associate_public_ip: quoted as string
  - enable_detailed_monitoring: quoted as string
- Change root_volume_size minimum from 8GB to 30GB
- Change root_volume_size default from 20GB to 30GB

ERROR FIXED:
InputError: Invalid input passed to action terraform:apply,
instance.variables.root_volume_size is not of a type(s) string,
instance.variables.associate_public_ip is not of a type(s) string,
instance.variables.enable_detailed_monitoring is not of a type(s) string

REASON:
Backstage terraform:apply action requires ALL variables as strings,
but template was passing numbers and booleans directly